FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY src/Worker.csproj ./
RUN dotnet restore Worker.csproj
COPY src/ ./
RUN dotnet publish Worker.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /out .
EXPOSE 8081
ENTRYPOINT ["dotnet","Worker.dll"]